### ISSUE TITLE
[FEATURE REQUEST] Try to improve Lighting performance

### ISSUE THREAD

**Issue by OpticFusion1** [OpticFusion1/Aurora#14]
**Is your feature request related to a problem? Please describe.**
Seems like a large reason for lag is lighting, this should be improved if possible.

**Describe the solution you'd like**
Improve lighting performance.

**Describe alternatives you've considered**
Leave as is w/ telling people to try disabling Lighting to improve performance

**Additional context**
N/A

**Comment by MrIvanPlays** [comment]
lighting on your side is already very well improved, the problem's inside the server. paper and starlight improve lighting a hell lot. what you need to do is recommend paper more.
