### ISSUE TITLE
[BUG] I can't get this to build

### ISSUE THREAD

**Issue by QuintenQVD0** [OpticFusion1/Aurora#3]
**Describe the bug**
when you try to build the project with java 17 it fails

**To Reproduce**
1. Download this repo
2. Change in the pom.xml line 105 from spigot to spigot-api so it can download the files
3. run mvn -B package --file pom.xml to build the project (( I tryed with github actions) and local same error)
4. See error: https://paste.gg/p/anonymous/2580b8ee511448debe60d39896bd8e5b

**Expected behavior**
It should not print this errors and give me a .jar file

**Screenshots**
no ( I don't think thats needed)

**Comment by OpticFusion1** [comment]
You need the NMS jar for 1.18.1
